### ISSUE TITLE
使用分组的SimpleRecyclerView，如果删除指定的分组下的某一个元素？

### ISSUE THREAD

**Issue by waitingal** [xingda920813/SimpleRecyclerView#3]
如果获取 title 和 child的position？

**Comment by xingda920813** [comment]
Library 已更新 1.5.5 版。

1.onTitleVHBind 和 onChildItemVHBind 方法现在增加了 int adapterPos, int titleOrderInAllTitles, int childOrderInCurrentGroup 参数：
- @param adapterPos ChildItem 在 Adapter 中的绝对位置 ( = holder.getAdapterPosition()).
- @param titleOrderInAllTitles 当前 ChildItem 所在 Group 在 List[Group] 中的相对位置.
- @param childOrderInCurrentGroup 当前 ChildItem 在 Group 中的相对位置.

2.GroupAdapter 增加了 2 个方法，若已知 Title 或 ChildItem 在 Adapter 中的绝对位置，需要得到 Title 对象、当前 Title 所在 Group 在 List[Group] 中的相对位置、ChildItem 对象和当前 ChildItem 在 Group 中的相对位置，可使用 GroupAdapter 上的 2 个方法：
/**
- 根据 Title 在 Adapter 中的绝对位置，
- 得到 Title 对象和当前 Title 所在 Group 在 List[Group] 中的相对位置.
- @param positionInRV_viewType_title Title 在 Adapter 中的绝对位置.
- @return TitleChildItemBean {Title title;  int titleOrder;}
  */
  TitleChildItemBean<Title, Void> getTitleWithOrder(int positionInRV_viewType_title)

/**
- 根据 ChildItem 在 Adapter 中的绝对位置，
- 得到 Title 对象、当前 Title 所在 Group 在 List[Group] 中的相对位置、
- ChildItem 对象和当前 ChildItem 在 Group 中的相对位置.
- @param positionInRV_viewType_childItem ChildItem 在 Adapter 中的绝对位置.
- @return TitleChildItemBean {Title title;  int titleOrder;
  ChildItem childItem;  int childOrder;}
  */
  TitleChildItemBean<Title, ChildItem> getTitleAndChildItem(int positionInRV_viewType_childItem)

3.增加了 OnGroupItemClickListener 和 OnGroupItemLongClickListener，同样增加了上述的 3 个参数。

详见更新过的 README.md 和 Library 代码注释。

Gradle 有缓存机制，若要让新版本即时生效，可将compile语句中的"+"改为"1.5.5"。

4.删除指定的分组下的某一个元素，可以用新增加的方法得到 titleOrder，然后根据 titleOrder，对 List<Group>.get(titleOrder)，得到当前的 Group 对象；

再用新增加的方法得到 childOrder，删除 Group<Title, ChildItem> 中的 List<ChildItem> 的第 childOrder 个元素 (Group.List<ChildItem>.remove(childOrder))；

最后 Adapter.notifyDataSetChanged() 即可。

**Comment by waitingal** [comment]
当某一组的子元素删除完后（getGroupList().get(group).childItemList.size()==0），调用getGroupList().remove(titleOrder); 后需要清除mTitleOrderPositionMap以及调用computeTotalCount()，否则 报错
java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
                                              at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                              at java.util.ArrayList.get(ArrayList.java:308)
                                              at com.xdandroid.simplerecyclerview.GroupAdapter.getTitleWithOrder(GroupAdapter.java:88)
                                              at com.xdandroid.simplerecyclerview.GroupAdapter.onViewHolderBind(GroupAdapter.java:52)
                                              at com.xdandroid.simplerecyclerview.Adapter.onBindViewHolder(Adapter.java:135)
                                              at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5768)
                                              at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5801)
                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5037)
                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
                                              at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                              at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:531)
                                              at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                              at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                              at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                              at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
                                              at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3069)
                                              at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
                                              at android.view.View.layout(View.java:16112)
                                              at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                              at android.view.View.layout(View.java:16112)

**Comment by xingda920813** [comment]
感谢反馈，果然是getCount的时候没有把上一次计算好的titleOrder与adapterPos的对应关系的Map清除掉的原因。

现在的 1.5.6 版，我自测List[Group].remove(int order)后调用notifyDataSetChanged()，已能够表现正常。

有什么问题欢迎进一步提出，感谢。
